---
editor_options: 
  chunk_output_type: console
---

# Add covariates to subsampled data

## Prepare libraries and data

```{r load_libs_data, eval=FALSE, message=FALSE, warning=FALSE}

# load libs
library(dplyr); library(readr)
library(stringr)
library(purrr)
library(raster)
library(glue)
library(velox)

# load saved data object
load("data_prelim_processing.rdata")
```

## Subsample data

Get 10 random (if available) observations of each species at each locality.

```{r subsample_data, eval=FALSE}
# subsample data for random 10 observations
dataSubsample <- dataGrouped %>% 
  plyr::dlply(c("scientific_name", "locality_id")) %>% 
  map_if(function(x) nrow(x) > 10, function(x) sample_n(x, 10, replace = FALSE)) %>% 
  bind_rows()

# remove full data
rm(dataGrouped)
```

## Add expertise score

```{r add_expertise, eval=FALSE}
# read in obs score and extract numbers
expertiseScore <- read_csv("data/dataObsRptrScore.csv") %>% 
  mutate(numObserver = str_extract(observer, "\\d+")) %>% 
  select(-observer)

# group seis consist of multiple observers
# in this case, seis need to have the highest expertise observer score
# as the associated covariate

# get unique observers per sei
dataSeiScore <- distinct(dataSubsample, sampling_event_identifier, observer_id) %>% 
  # make list column of observers
  mutate(observers = str_split(observer_id, ",")) %>% 
  unnest(cols = c(observers)) %>% 
  # add numeric observer id
  mutate(numObserver = str_extract(observers, "\\d+")) %>% 
  # now get distinct sei and observer id numeric
  distinct(sampling_event_identifier, numObserver)

# now add expertise score to sei
dataSeiScore <- left_join(dataSeiScore, expertiseScore,
                         by="numObserver") %>% 
  # get max expertise score per sei
  group_by(sampling_event_identifier) %>% 
  summarise(expertise = max(rptrScore))

# add to dataCovar
dataSubsample <- left_join(dataSubsample, dataSeiScore, by = "sampling_event_identifier")

# remove data without expertise score
dataSubsample <- filter(dataSubsample, !is.na(expertise))

```

## Add landscape covariates

```{r add_landcovars, eval=FALSE}

# list landscape covariate stacks
landscape_files <- list.files("data/spatial/", pattern = "landscape", full.names = T)

# read in as stacks
landscape_data <- map(landscape_files, stack)

# get proper names
elev_names <- c("elev", "slope", "aspect")
evi_names <- c("evi_01", "evi_07", "evi_10")
chelsa_names <- c("chelsa_bio10_04", "chelsa_bio10_17", "chelsa_bio10_18",
                  "chelsa_prec", "chelsa_temp")

landscape_names <- map(landscape_data, names) %>%
  map(function(chr){as.character(glue('{str_sub(chr,1,20)}_{c(elev_names, evi_names, chelsa_names, "landcover")}'))})

# assign names
for(i in 1:length(landscape_data)){
  names(landscape_data[[i]]) <- landscape_names[[i]]
}
```

## Construct 2.5km buffer around subsampled points

```{r point_buffer, eval=FALSE}
# assign neighbourhood radius in m
neighbourhood_radius <- 2500

# get distinct points and make buffer
ebird_buff <- dataSubsample %>% 
  distinct(locality_id, latitude, longitude) %>% 
  # convert to spatial features
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326) %>% 
  # transform to modis projection
  st_transform(crs = 32643) %>% 
  # buffer to create neighborhood around each point
  st_buffer(dist = neighbourhood_radius)

```

## Get mean landscape values

```{r mean_landscape, eval=FALSE}
# get area mean for all preds except landcover, which is the last one
env_area_mean <- purrr::map(landscape_data, function(stk){
  stk <- stk[[-dim(stk)[3]]] # removing landcover here
  velstk <- velox(stk)
  dextr <- velstk$extract(sp = ebird_buff, df = TRUE, 
                          fun = function(x)mean(x, na.rm=T))
  names(dextr) <- c("id", names(stk))
  return(as_tibble(dextr))
})

# run a reduce leftjoin on the data
env_area_mean <- purrr::reduce(env_area_mean, left_join)
# rename to be clear which are mean-area vars
names(env_area_mean) <- c("id", glue::glue('area_mean_{names(env_area_mean)[-1]}'))
```

## Get proportional landcover

```{r pland, eval=FALSE}
# WIP
```

# WIP