--- 
knit: "bookdown::render_book"
title: "Using citizen science to parse climatic and landcover influences on bird occupancy within a tropical biodiversity hotspot"
author:
    - Vijay Ramesh
    - Pratik R. Gupte
    - Morgan W. Tingley
    - VV Robin
    - Ruth DeFries
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    fig_caption: yes
bibliography: [refs.bib]
biblio-style: apalike
link-citations: yes
github-repo: pratikunterwegs/eBirdOccupancy
description: "Influence of land cover and climate on the occupancy of avian distributions along a tropical montane gradient"

---

# Introduction

This is the `bookdown` version containing analysis that models associations between environmental predictors (climate and landcover) and citizen science observations of birds across the Nilgiri and Anamalai hills of the Western Ghats Biodiversity Hotspot. 

Methods and format are derived from [Strimas-Mackey et al.](https://cornelllabofornithology.github.io/ebird-best-practices/).

## Attribution

Please contact the following in case of interest in the project.

- Vijay Ramesh (lead author)
    - PhD student, Columbia University

- Pratik Gupte (repo maintainer)
    - PhD student, University of Groningen

## Data access

The data used in this work are available from [eBird](http://ebird.org/data/download).

## Data processing

The data processing for this project is described in the following sections. Navigate through them using the links in the sidebar.